### ISSUE TITLE
Redshift: LOG10 rule needs cast

### ISSUE THREAD

**Issue by alondhe** [OHDSI/SqlRender#64] opened 2017-04-04 22:45 UTC
The rule for LOG10 yields log(@expression) in Redshift, looks like that isn't supported:
`function "log(numeric,numeric)" not supported.`

Perhaps the translation could be log(cast(@expression) as real), like the pattern for LN.

**Comment by schuemie** [comment] 2017-04-05 05:01
The error message indicates two numeric values were provided, and RedShift doesn't know what to do with that.

However, these work fine:
```sql
SELECT LOG(CAST(10 AS NUMERIC));
SELECT LOG(CAST(10 AS INT));
SELECT LOG(CAST(10 AS REAL));
```

In fact, these also work fine, so I'm starting to wonder why we have the cast for LN:
```sql
SELECT LN(CAST(10 AS NUMERIC));
SELECT LN(CAST(10 AS INT));
SELECT LN(CAST(10 AS REAL));
```

**Comment by alondhe** [comment] 2017-04-05 07:14
This arose from a query in Atlas's patient profiles page. The issue may be simply with how that LOG10 function is composed in that query. It tries to blend two variable types with the log10 call, a count(*) + a float. I think this is just an Atlas issue, it should probably just encapsulate the expression with mixed types in a cast, right? I'll raise an issue on that repo.

**Comment by schuemie** [comment] 2017-04-05 07:35
I don't know, there might be something else going on in that query that has nothing to do with the LOG10. This also works fine:
```sql
SELECT LOG(COUNT(*) + CAST(10 AS FLOAT)) FROM person;
```

**Comment by schuemie** [comment] 2017-04-05 07:37
Maybe the query is using LOG(number, base)? (for a base other than e or 10)

**Comment by schuemie** [comment] 2017-04-05 08:19
I've added support for translation of LOG(number,base) to the various dialects [here](https://github.com/OHDSI/SqlRender/commit/0aabdf11487bd72f69e64ea42ebf890ecf67fe55). Could you check if this solves the problem?

**Comment by alondhe** [comment] 2017-04-06 18:21
I think those rules are good, but I don't think they fix the WebAPI/Atlas issue. The call in WebAPI to support patient profiles is to use this:
`log10(abs(count(*) + 0.01))`

which translates to Redshift as:
`log(abs(count(*) + 0.01))`

but needs to be this (in OHDSql):
`log10(abs(cast(count(*) + 0.01 as real)))`

I'm opening an issue in WebAPI, but not sure which is the best place for this change to happen. Casting the inner expression to real in the translateSql engine would ensure that anyone's usage of LOG10 has an expression that is of uniform type, but maybe this is too heavy handed and should be an application consideration?

**Comment by schuemie** [comment] 2017-04-07 06:54
Ah, I now see what the problem is. RedShift has a weird [NUMERIC(precision,scale)](http://docs.aws.amazon.com/redshift/latest/dg/r_Numeric_types201.html#r_Numeric_types201-decimal-or-numeric-type) type, and the log function hasn't been implemented in RedShift for that weird type. It just so happens that `COUNT(*) + 0.01` produces this weird type.

In this case I would argue the best solution is to add the cast in SqlRender as you originally suggested. I'll get right on it.

**Comment by schuemie** [comment] 2017-04-07 07:21
Should be fixed in https://github.com/OHDSI/SqlRender/commit/b26b3e11e1c64535daab1ce2c3bf7bc2a01ebf18

**Closed by schuemie** 2017-04-07 07:21 UTC
