### ISSUE TITLE
INSERT INTO translated to CREATE TABLE

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/SqlRender#304] opened 2022-09-26 09:48 UTC
SqlRender returns an invalid query when translating a complex sql (attached here) that inserts into an existing table.

In short, two unexpected things happen:
- a `CREATE TABLE @resultSchema.@resultTable SELECT * AS` is inserted in one of the union queries (using the schema and table from the original insert into)
- the original insert into at the bottom of the query is malformed to `INSERT FROM`. Both the 'INTO' and schema/table names are removed.

I tried finding the bit of sql that triggers the issue, but no luck so far. The issue disappears when removing some unions or some sub queries. Also, when rewriting the query without the main CTE (as one big subquery), the issue also disappeared.

I did isolate the issue to `translate()` and issue is with all dialects except for sql server and synapse.

[sql_unioned.sql.txt](https://github.com/OHDSI/SqlRender/files/9644910/sql_unioned.sql.txt)

**Comment by schuemie** [comment] 2022-09-27 09:00
I'm not yet sure what the problem is, but I've been able to isolate it to a small snippet. This still shows the problem:

```sql
WITH cte_all
AS (
	SELECT * FROM @cdmSchema.MEASUREMENT m
		
	UNION ALL
	
	SELECT 	'(Glucose [Mass/volume] in Serum or Plasma --12 hours fasting)' AS check_description
	)
INSERT INTO @resultsSchema.@resultsTable
SELECT *
FROM cte_all;
```
If I remove either the `(` or one of the `-` in the quoted string the problem goes away. The odd thing of course is that this is inside quotes, so should be ignored by SqlRender.

**Comment by schuemie** [comment] 2022-09-27 11:50
I think I found the issue. Checking for SQL comments didn't check whether the tokens were inside quotes. Should be fixed now in the develop branch. Could you give it a try?

**Comment by MaximMoinat** [comment] 2022-09-27 12:48
Thanks for the quick investigation, great you found the issue. I could have spend another day finding that.
However, the fix in develop does not work for me, both on the original query and the isolated snippet you shared.
<img width="837" alt="image" src="https://user-images.githubusercontent.com/17825660/192530184-7c27678e-1803-4360-a2be-ca4758565cef.png">

**Comment by schuemie** [comment] 2022-09-28 06:28
That same code produces the correct result on my machine, so I think something went wrong when updating the package. Do you see a message about the Java library version not matching the package version when you load SqlRender? 

A problem when updating an R package with an embedded Java library (like SqlRender) is that the Java library gets loaded into the Java VM, and then the jar file is locked and cannot be replaced until the VM is shut down. The only way to achieve that is to stop all R sessions on the machine, open only one session (make sure you don't load the previous R session at start), and then do the update.

**Comment by MaximMoinat** [comment] 2022-09-28 09:53
Restarting R session indeed loaded the package now correctly. 
And the fix works for me now as well. Thanks!

**Closed** 2022-12-02 09:21 UTC
Labels: bug
