### ISSUE TITLE
SqlRender::translate puts table and schema names in lowercase on bigquery causing errors if tables are uppercase.

### ISSUE THREAD

**Issue by ablack3** [OHDSI/SqlRender#293] opened 2022-08-17 15:07 UTC
SqlRender::translate seems to map table names to lower case when translating to bigquery. This is problematic if table names are uppercase in the database since bigquery is case sensitive. 

It's not 100% clear if table names should be uppercase or lowercase in case sensitive database systems. The CDM spec seems to imply that they should be uppercase (e.g. [CONDITION](https://ohdsi.github.io/CommonDataModel/cdm54.html#CONDITION_OCCURRENCE)) but the DDL generated for BigQuery creates a lowercase condition table on bigquery.

We are discussing the case sensitivity spec in this issue: https://github.com/OHDSI/CommonDataModel/issues/509

``` r
# Expected output: "select * From TABLE"
# Actual Output
SqlRender::translate("select * From TABLE", "bigquery")
#> [1] "select * from table"

SqlRender::translate("select * From SCHEMA.TABLE", "bigquery")
#> [1] "select * from schema.table"

# Interestingly SqlRender does not perform the lowercase transformation for postgres.
SqlRender::translate("select * From SCHEMA.TABLE", "postgresql")
#> [1] "select * From SCHEMA.TABLE"
```

<sup>Created on 2022-08-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I think the relevant code is here: https://github.com/OHDSI/SqlRender/blob/4e75e09c35ccf7e587decf0ef33bf0e223d38819/java/org/ohdsi/sql/BigQuerySparkTranslate.java#L344

**Comment by schuemie** [comment] 2022-09-02 14:26
Duplicate of https://github.com/OHDSI/SqlRender/issues/273

**Closed** 2023-01-21 03:04 UTC
Labels: duplicate
